### ISSUE TITLE
Error Class '\kcone87\Yii2LdapAuth\Model\LdapUser' not found

### ISSUE THREAD

**Issue by evgeniysibenkov** [kcone87/yii2-ldap-auth#1]
An error occurs after connecting the extension Error Class '\kcone87\Yii2LdapAuth\Model\LdapUser' not found

**Comment by kcone87** [comment]
Hi, have you installed the extension?
Check your composer.json if the extension exists

**Comment by evgeniysibenkov** [comment]
I installed it without composer. in the autoload_psr4.php file I registered 
'kcone87\\Yii2LdapAuth\\' => array($vendorDir . '/kcone87/yii2-ldap-auth/src'),

**Comment by evgeniysibenkov** [comment]
in the extensions.php file I registered
'kcone87/yii2-ldap-auth' =>
            array (
                'name' => 'kcone87/yii2-ldap-auth',
                'version' => '0.1.0.0',
                'alias' =>
                    array (
                        '@kcone87/yii2ldapauth' => $vendorDir . '/kcone87/yii2-ldap-auth/src',
                    ),
            ),

**Comment by kcone87** [comment]
check this link https://github.com/kcone87/yii2-ldap-auth and Make sure under Model there's a file called LdapUser

**Comment by kcone87** [comment]
@evgeniysibenkov  try updating the package to get the latest changes that I pushed yesterday
